Update azure-pipelines-1.yml for Azure Pipelines

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -1,6 +1,8 @@
 # Sample Azure Pipeline YAML with one script task
 trigger:
 - main
+variables:
+  globalVariableName: ''
 
 pool:
   vmImage: 'ubuntu-latest'
@@ -9,17 +11,25 @@ steps:
 - script: |
     echo "Hello, World!"
     echo "This is a sample script task."
-    exit  1
+    if [ $? -ne 0 ]; then
+        echo "##vso[task.setvariable variable=globalVariableName]Run a 1"
+    fi
   displayName: 'Run a 1'
-  name: taks_1
-  continueOnError: true
 - script: |
     echo "Hello, World!"
     echo "This is a sample script task."
+    if [ $? -ne 0 ]; then
+        echo "##vso[task.setvariable variable=globalVariableName]Run a 2"
+    fi
     exit 1
   displayName: 'Run a 2'
-  name: task_2
-  continueOnError: true
+- script: |
+    echo "Hello, World!"
+    echo "This is a sample script task."
+    if [ $? -ne 0 ]; then
+        echo "##vso[task.setvariable variable=globalVariableName]Run a 2"
+    fi
+  displayName: 'Run a 3'
 - script: |
     cd $(Agent.WorkFolder)/1/a
     ls
@@ -29,8 +39,8 @@ steps:
     ls
     cd $(Agent.WorkFolder)/_temp
     ls
-  displayName: 'Run a 3'
-  name: task_3
+    echo "Failed task name is: $(globalVariableName)."
+  displayName: 'Run a 4'
   condition: always()
 - script: |
       # Publish logs from a specified directory
